### PR TITLE
Add support for stderr sinks

### PR DESCRIPTION
**Pull request by nextsilicon-itay-bookstein**
Hi!

We wanted to use stderr sinks and I thought this might be of general interest, so I wrote this PR to see if you find it useful :)

### CODE REVIEW

**Comment by guangie88** [comment]
Thanks for the feature, no problem with it, except it's just failing formatting checks.

Could I trouble you to just run `./run-clang-format.sh` (you will need Docker CLI) to auto-fix the issue?

The detailed instructions for the auto-fix is here if needed:
https://github.com/guangie88/spdlog_setup#contributions

---

If it's still too much trouble to set up Docker, the formatting is basically preferring this:

```diff
--- a/include/spdlog_setup/details/conf_impl.h
+++ b/include/spdlog_setup/details/conf_impl.h
@@ -902,10 +902,10 @@ inline auto sink_from_sink_type(
     using spdlog::sinks::rotating_file_sink_mt;
     using spdlog::sinks::rotating_file_sink_st;
     using spdlog::sinks::sink;
-    using spdlog::sinks::stdout_sink_mt;
-    using spdlog::sinks::stdout_sink_st;
     using spdlog::sinks::stderr_sink_mt;
     using spdlog::sinks::stderr_sink_st;
+    using spdlog::sinks::stdout_sink_mt;
+    using spdlog::sinks::stdout_sink_st;
```

**Comment by guangie88** [comment]
Also could you help to update the `README.md` under https://github.com/guangie88/spdlog_setup#supported-sinks, to include the two new sinks?

Thanks!

**Comment by nextsilicon-itay-bookstein** [comment]
Gladly, done both 👍

**Review by guangie88 — APPROVED** [review]
LGTM

**Pull request merged**
